; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24247.2 

; Generated by VC++ for Common Language Runtime
.file "C:\COMPxxxx\GUIpng\x64\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.cpp"
